//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehir
    {
        public int SehirId { get; set; }
        public string Adi { get; set; }
        public string Nufusu { get; set; }
        public string Bolgesi { get; set; }
        public string Ulkesi { get; set; }
        public Nullable<int> KurutulusYili { get; set; }
    }
}
